const KEY='ama-fighter-coach-v2';
const domains={
'Mechanics':{icon:'⚔',desc:'Guard, blocks, returns, recovery, and clean weapon mechanics.',standards:['Perform the movement slowly with a stable guard.','Repeat the skill cleanly during a structured drill.','Keep the mechanic intact under live pressure.','Diagnose and teach common mechanic errors.']},
'Movement':{icon:'✦',desc:'Balance, angles, range, tempo, entries, and exits.',standards:['Move without crossing feet or collapsing stance.','Use controlled entries and exits in drills.','Create useful angles and range under pressure.','Coach another fighter through entries, exits, and balance.']},
'Geometry':{icon:'△',desc:'Lines, lanes, cones, center line, and range zones.',standards:['Name the basic range and line in a static example.','Move to improve the line during a drill.','Explain why a position succeeded or failed in sparring.','Teach geometry with a simple physical demonstration.']},
'Intelligence':{icon:'◉',desc:'Cold reads, hot reads, opponent models, planning, and adaptation.',standards:['Notice one obvious opponent habit.','Build a simple plan from a read.','Update the plan when new information appears.','Analyze another fighter and coach a useful adjustment.']},
'Deception':{icon:'♢',desc:'Believable threats, baits, conditioning, and simple traps.',standards:['Make a feint that resembles a real attack.','Create a predictable reaction in a drill.','Condition and break a pattern during live fighting.','Teach deception without adding unnecessary complexity.']},
'Drill Discipline':{icon:'⌁',desc:'Focused repetition, clean constraints, pressure progression, and review.',standards:['Follow a drill without turning it into free sparring.','Practice one goal while ignoring unrelated noise.','Pressure-test a skill through increasingly live stages.','Design a clear drill with a measurable success standard.']},
'Leadership':{icon:'♜',desc:'Teaching, feedback, service, humility, and continuity.',standards:['Help when asked and model safe habits.','Give one specific, actionable correction.','Support newer fighters and run a short guided drill.','Run a lesson that makes other fighters measurably stronger.']}
};
const drills=[
{name:'Needling',domain:'Movement',purpose:'Fine range control and entry timing.',how:'Take repeated micro-steps in and out of range. Rebuild stance after every step.',success:'No crossed feet; balanced on every freeze.'},
{name:'Alphabet Footwork',domain:'Movement',purpose:'Multi-directional movement, pivots, and balance.',how:'Trace large letters using deliberate steps while keeping guard organized.',success:'Direction changes without stance collapse.'},
{name:'Two-Target Block-Strike',domain:'Mechanics',purpose:'Pattern recognition, defense, and reliable returns.',how:'Partner attacks only two agreed targets. Block and return with control.',success:'Clean defense and return without rushing.'},
{name:'ABA',domain:'Mechanics',purpose:'Attack, recover, defend, continue.',how:'A attacks; B blocks and attacks; A blocks and attacks again. Build speed gradually.',success:'Guard and stance survive every transition.'},
{name:'Freeze-and-Name',domain:'Geometry',purpose:'Turn range and angle into visible information.',how:'During light movement, freeze and name range, useful line, threat, and exit.',success:'Explain the position in one clear sentence.'},
{name:'Range Gates',domain:'Geometry',purpose:'Learn where exchanges become dangerous or advantageous.',how:'Move between safe, counter, and exchange ranges before adding one permitted shot.',success:'Enter and leave the chosen range on purpose.'},
{name:'Tell Hunt',domain:'Intelligence',purpose:'Build hot reads from repeated information.',how:'Observe shoulders, feet, guard motion, and preferred responses before exploiting them.',success:'Identify one behavior that predicts a choice.'},
{name:'One-Plan Sparring',domain:'Intelligence',purpose:'Practice planning and honest adaptation.',how:'State one simple plan before each bout. Change only one part when evidence demands it.',success:'Plan changes because of evidence, not frustration.'},
{name:'Feint → Reaction',domain:'Deception',purpose:'Make threats that cause intentional reactions.',how:'Choose one real attack and one matching feint. Make the defense begin before committing.',success:'Partner reacts to the feint before the real attack.'},
{name:'Condition & Break',domain:'Deception',purpose:'Create a pattern, then exploit expectation.',how:'Repeat a believable setup, then preserve the setup while changing the finish.',success:'Opponent commits to the expected response.'},
{name:'Constraint Round',domain:'Drill Discipline',purpose:'Keep one learning goal visible under pressure.',how:'Fight normally with one constraint: only diagonal entries score, block twice first, or forbid your favorite shot.',success:'Obey the constraint even when losing.'},
{name:'Pressure Ladder',domain:'Drill Discipline',purpose:'Bridge clean practice into real performance.',how:'Use the same skill in clean drill, constrained sparring, open sparring, then one consequence round.',success:'The same cue remains usable as pressure rises.'},
{name:'Teach-Back',domain:'Leadership',purpose:'Expose gaps by explaining the skill simply.',how:'Teach one concept in under two minutes, demonstrate it, give one drill, then ask for teach-back.',success:'Learner can state the concept and perform the basic action.'}
];
const defaults=()=>({domains:Object.fromEntries(Object.keys(domains).map(k=>[k,1])),marks:0,sessions:[],fights:[],teachings:[],ledger:[],selectedDuration:5,selectedFocus:'Movement'});
let state;try{state={...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state=defaults()}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=t=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(t));
const weakest=()=>{let m=Math.min(...Object.values(state.domains));return Object.keys(state.domains).find(k=>state.domains[k]===m)};
function nav(view){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===view));document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===view));window.scrollTo(0,0);render()}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
function renderHall(){let w=weakest(),d=domains[w],lvl=state.domains[w],dr=drills.find(x=>x.domain===w)||drills[0];document.getElementById('todayTitle').textContent=w;document.getElementById('todayLevel').textContent=['Beginning','Developing','Reliable','Teaching Level'][lvl-1];document.getElementById('todayWhy').textContent=`Your lowest current assessment is ${w}. Give it focused work before adding more complexity.`;document.getElementById('todayDrill').textContent=`${dr.name} — 5 minutes`;document.getElementById('todayFight').textContent=d.standards[Math.min(lvl,3)];document.getElementById('marks').textContent=state.marks;let whole=[['Body','⚔',Math.round(((state.domains.Mechanics+state.domains.Movement)/8)*100)],['Craft','⌁',Math.round(((state.domains.Mechanics+state.domains['Drill Discipline'])/8)*100)],['Mind','◉',Math.round(((state.domains.Geometry+state.domains.Intelligence+state.domains.Deception)/12)*100)],['Character','♜',Math.round(((state.domains['Drill Discipline']+state.domains.Leadership)/8)*100)],['Fellowship','✦',Math.min(100,20+state.teachings.length*15)]];document.getElementById('pillars').innerHTML=whole.map(x=>`<div class="pillar"><div class="pillar-icon">${x[1]}</div><span>${x[0]}</span><div class="pillar-meter"><i style="width:${x[2]}%"></i></div></div>`).join('')}
function populate(){let opts=Object.keys(domains).map(k=>`<option>${k}</option>`).join('');document.getElementById('domainSelect').innerHTML=opts;document.getElementById('fightDomain').innerHTML=opts;document.getElementById('domainSelect').value=state.selectedFocus}
document.getElementById('durationRow').onclick=e=>{let b=e.target.closest('[data-minutes]');if(!b)return;state.selectedDuration=+b.dataset.minutes;save();document.querySelectorAll('[data-minutes]').forEach(x=>x.classList.toggle('selected',x===b))};
document.getElementById('domainSelect').onchange=e=>{state.selectedFocus=e.target.value;save()};
document.getElementById('generateSession').onclick=()=>{let focus=document.getElementById('domainSelect').value,min=state.selectedDuration,list=drills.filter(x=>x.domain===focus);if(!list.length)list=drills;let chosen=list[Date.now()%list.length],reps=min===5?'2 focused rounds':min===10?'3 focused rounds plus light pressure':'4 focused rounds, constrained sparring, then review';document.getElementById('sessionCard').innerHTML=`<span class="kicker">FORGED SESSION</span><h3>${chosen.name}</h3><div class="session-meta"><span>${focus}</span><span>${min} minutes</span></div><p>${chosen.purpose}</p><ol class="steps"><li>Warm up the exact movement slowly for about one minute.</li><li>${chosen.how}</li><li>Complete ${reps}.</li><li>Pressure-test only the same skill; do not add unrelated goals.</li><li>Finish by naming one thing that improved and one next correction.</li></ol><div class="session-footer"><b>Success standard:</b> ${chosen.success}</div><button id="completeSession" class="primary wide" style="margin-top:12px">Record Session Complete</button>`;document.getElementById('completeSession').onclick=()=>{let t=Date.now();state.sessions.unshift({focus,name:chosen.name,min,date:t});state.ledger.unshift({type:'train',title:`${min}-minute ${focus} session`,detail:chosen.name,date:t});state.marks+=2;save();document.getElementById('sessionCard').innerHTML='<h3>Session recorded.</h3><p>The work is now in your Chronicle. Carry one correction into live fighting.</p>';render()}}
document.getElementById('fightForm').onsubmit=e=>{e.preventDefault();let f=Object.fromEntries(new FormData(e.target));f.date=Date.now();state.fights.unshift(f);state.ledger.unshift({type:'fight',title:`${f.domain} after-action review`,detail:f.adjustment,date:f.date});state.marks+=1;save();e.target.reset();document.getElementById('fightSaved').hidden=false;setTimeout(()=>document.getElementById('fightSaved').hidden=true,2500);render()};
function renderPath(){let labels=['Beginning','Developing','Reliable','Teaching Level'];document.getElementById('domainCards').innerHTML=Object.entries(domains).map(([name,d])=>{let lvl=state.domains[name];return `<article class="domain-card"><div class="domain-top"><div><span class="kicker">${d.icon} DOMAIN</span><h3>${name}</h3></div><span class="difficulty">${labels[lvl-1]}</span></div><p>${d.desc}</p><div class="rating">${[1,2,3,4].map(n=>`<button class="${n<=lvl?'on':''}" data-rate="${name}" data-level="${n}">${n}</button>`).join('')}</div><div class="rating-label">${labels[lvl-1]}</div><div class="standard"><b>Current standard:</b> ${d.standards[lvl-1]}</div></article>`}).join('');document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{state.domains[b.dataset.rate]=+b.dataset.level;save();render()})}
document.getElementById('pressureLadder').innerHTML=[['Clean Drill','Build the mechanic without noise.'],['Constrained Sparring','Test one skill with limited choices.'],['Open Sparring','Apply the skill in chaos with one private goal.'],['Bear Pit','Keep the cue through fatigue and repeated opponents.'],['Tournament Round','Execute a simple plan under consequence.'],['After-Action Review','What happened? Why? What next?']].map((x,i)=>`<div class="ladder-item"><b>${i+1}</b><div><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join('');
document.getElementById('teachForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.date=Date.now();state.teachings.unshift(o);state.ledger.unshift({type:'teach',title:`Taught ${o.topic}`,detail:`Helped ${o.student}`,date:o.date});state.marks+=3;save();e.target.reset();render()};
function renderChronicle(){document.getElementById('statSessions').textContent=state.sessions.length;document.getElementById('statReviews').textContent=state.fights.length;document.getElementById('statTeaching').textContent=state.teachings.length;document.getElementById('chronicleList').innerHTML=state.ledger.length?state.ledger.slice(0,20).map(x=>`<div class="entry"><div class="entry-top"><strong>${esc(x.title)}</strong><time>${date(x.date)}</time></div><p>${esc(x.detail)}</p></div>`).join(''):'<div class="empty">Your Chronicle is blank. Train deliberately and record what you learn.</div>'}
document.getElementById('resetData').onclick=()=>{if(confirm('Reset all Fighter Coach prototype data on this device?')){state=defaults();save();render()}};
function render(){renderHall();renderPath();renderChronicle()}
populate();document.querySelectorAll('[data-minutes]').forEach(x=>x.classList.toggle('selected',+x.dataset.minutes===state.selectedDuration));render();
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;let b=document.getElementById('installButton');b.hidden=false;b.onclick=async()=>{await deferred.prompt();deferred=null;b.hidden=true}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});