export type DomainName =
  | "Mechanics"
  | "Movement"
  | "Geometry"
  | "Intelligence"
  | "Deception"
  | "Drill Discipline"
  | "Leadership";

export type TrainingMode = "Solo" | "Partner" | "Warband";

export type DomainDefinition = {
  icon: string;
  short: string;
  description: string;
  primer: string;
  color: string;
  standards: string[];
};

export type ForgeTemplate = {
  id: string;
  domain: DomainName;
  title: string;
  purpose: string;
  drill: string;
  pressure: string;
  standard: string;
  cue: string;
  reflection: string;
  adaptations: Record<TrainingMode, string>;
  source: string;
  gear: string;
};

export const DOMAIN_ORDER: DomainName[] = [
  "Mechanics",
  "Movement",
  "Geometry",
  "Intelligence",
  "Deception",
  "Drill Discipline",
  "Leadership",
];

export const DOMAINS: Record<DomainName, DomainDefinition> = {
  Mechanics: {
    icon: "⚔",
    short: "Weapon craft",
    description: "Guard, blocks, shots, returns, recovery, and clean weapon mechanics.",
    primer: "Rehearse the chosen motion at half speed. Finish every action in a position that can defend and act again.",
    color: "#b97832",
    standards: [
      "Perform the movement slowly with a stable guard.",
      "Repeat the skill cleanly during a structured drill.",
      "Keep the mechanic intact under live pressure.",
      "Diagnose and teach common mechanic errors.",
    ],
  },
  Movement: {
    icon: "✦",
    short: "Footwork",
    description: "Balance, angles, tempo, entries, exits, and the feet beneath every technique.",
    primer: "Move through short entries, exits, and direction changes. Reset the stance after each step before adding speed.",
    color: "#9d7e2d",
    standards: [
      "Move without crossing feet or collapsing stance.",
      "Use controlled entries and exits in drills.",
      "Create useful angles and range under pressure.",
      "Coach another fighter through entries, exits, and balance.",
    ],
  },
  Geometry: {
    icon: "△",
    short: "Range & lines",
    description: "Range zones, lanes, cones, center lines, and position before the shot.",
    primer: "Map the space before attacking: name the range, the open lane, the largest threat, and the safest exit.",
    color: "#6f8d76",
    standards: [
      "Name the basic range and line in a static example.",
      "Move to improve the line during a drill.",
      "Explain why a position succeeded or failed in sparring.",
      "Teach geometry with a simple physical demonstration.",
    ],
  },
  Intelligence: {
    icon: "◉",
    short: "Fight IQ",
    description: "Cold reads, hot reads, opponent models, planning, and adaptation.",
    primer: "Observe before solving. Identify one visible fact, one likely preference, and one question the next exchange can answer.",
    color: "#527f83",
    standards: [
      "Notice one obvious opponent habit.",
      "Build a simple plan from a read.",
      "Update the plan when new information appears.",
      "Analyze another fighter and coach a useful adjustment.",
    ],
  },
  Deception: {
    icon: "◇",
    short: "Setups",
    description: "Believable threats, baits, conditioning, change-ups, and simple traps.",
    primer: "Rehearse the real attack first. A useful lie must begin like a threat that could honestly land.",
    color: "#785f8d",
    standards: [
      "Make a feint that resembles a real attack.",
      "Create a predictable reaction in a drill.",
      "Condition and break a pattern during live fighting.",
      "Teach deception without adding unnecessary complexity.",
    ],
  },
  "Drill Discipline": {
    icon: "⌁",
    short: "Practice craft",
    description: "Focused repetition, clean constraints, pressure progression, and review.",
    primer: "State one learning goal and one success standard aloud. Remove any rule or activity that does not serve them.",
    color: "#9c633a",
    standards: [
      "Follow a drill without turning it into free sparring.",
      "Practice one goal while ignoring unrelated noise.",
      "Pressure-test a skill through increasingly live stages.",
      "Design a clear drill with a measurable success standard.",
    ],
  },
  Leadership: {
    icon: "♜",
    short: "Service",
    description: "Teaching, feedback, safety, service, humility, and continuity.",
    primer: "Choose one idea you can explain in one sentence, demonstrate once, and verify through another fighter's action.",
    color: "#9f493e",
    standards: [
      "Help when asked and model safe habits.",
      "Give one specific, actionable correction.",
      "Support newer fighters and run a short guided drill.",
      "Run a lesson that makes other fighters measurably stronger.",
    ],
  },
};

export const QUESTS: Record<DomainName, { title: string; text: string }> = {
  Mechanics: { title: "Keep the Guard Alive", text: "Choose one mechanic that breaks under speed. Rebuild it slowly, then add honest pressure." },
  Movement: { title: "Own Your Range", text: "Practice controlled entries and exits while preserving the stance beneath them." },
  Geometry: { title: "Win the Line First", text: "Improve the position until the attack requires less speed, reach, and hope." },
  Intelligence: { title: "Fight for Information", text: "Spend early exchanges discovering what the opponent prefers before forcing a plan." },
  Deception: { title: "Make the Lie Believable", text: "Use a real threat to create a predictable answer, then change the finish." },
  "Drill Discipline": { title: "Remove the Noise", text: "Train one skill under one clear constraint and refuse to turn it into ordinary sparring." },
  Leadership: { title: "Light Another Lantern", text: "Teach one useful thing simply enough that another fighter can use it today." },
};

const t = (
  id: string,
  domain: DomainName,
  title: string,
  purpose: string,
  drill: string,
  pressure: string,
  standard: string,
  cue: string,
  reflection: string,
  solo: string,
  partner: string,
  warband: string,
  source: string,
  gear: string,
): ForgeTemplate => ({
  id,
  domain,
  title,
  purpose,
  drill,
  pressure,
  standard,
  cue,
  reflection,
  adaptations: { Solo: solo, Partner: partner, Warband: warband },
  source,
  gear,
});

export const FORGE_TEMPLATES: ForgeTemplate[] = [
  t("mec-guard-return", "Mechanics", "The Guard That Returns", "Make every attack recover into useful defense.", "Choose one dependable shot. Throw it at half speed, pause at the hit line, then rebuild the guard without retracting wildly or dropping the hand. Repeat from both successful and missed positions.", "Permit only that shot in short exchanges. A point counts only when the fighter could immediately defend the primary return.", "Eight of ten attacks finish in a balanced, live guard.", "The shot is not finished until the guard returns.", "Which part of recovery failed first: hand, elbow, shoulder, or feet?", "Use a pell, hanging target, or marked air target; freeze after every swing and inspect the recovery.", "The receiver feeds one predictable return after each shot, slowly at first and then naturally.", "Run three-person lanes: attacker, returner, observer. Rotate after five clean repetitions.", "SKBC · Intermediate Single Sword", "Sword; optional pell"),
  t("mec-pendulum", "Mechanics", "Pendulum Block", "Build compact blocks that move the weapon, not the whole body.", "Hold the sword away from the body in a stable guard. Move the tip through a small pendulum arc while the hand travels only far enough to close the attack lane. Reset without winding up.", "Add alternating high and low feeds. The defender must close the correct lane without chasing the attacking weapon.", "Ten controlled blocks protect the target without oversized motion.", "Close the lane; do not swat the sword.", "Did your hand travel farther than the threat required?", "Use a reflection, slow-motion shadow feeds, or a suspended foam noodle as the incoming line.", "Feeder presents two agreed lines, then gradually varies timing while keeping contact light.", "Form a feed circle around one defender; only one feeder moves at a time and an observer watches hand travel.", "SKBC · Intermediate Single Sword", "Sword; partner weapon optional"),
  t("mec-two-target", "Mechanics", "Two-Target Block–Strike", "Link recognition, defense, and a safe primary return.", "Select two legal targets and two matching defensive closures. Move slowly through attack, block, and primary return until each transition becomes one organized action.", "Increase uncertainty by allowing either target and variable timing. Keep the target set narrow so quality remains visible.", "Complete twenty exchanges with correct target recognition and no panic swing.", "See the line, close it, return safely.", "Which target or return caused your structure to unravel?", "Alternate imagined feeds to two marked targets; use a mirror or video to audit block position.", "Use classic block–strike with exactly two target choices; pause whenever structure breaks.", "Pair into lanes and rotate feeders every minute; observers count clean transitions rather than hits.", "SKBC · Drills and Training", "Two safe weapons"),
  t("mec-aba", "Mechanics", "ABA Recovery Chain", "Keep mechanics intact across attack–defend–attack transitions.", "Rehearse the three-action chain: attack, recover to block, then make the next attack. Move slowly enough that each action grows from the last instead of resetting from scratch.", "Run constrained exchanges where only a clean three-action chain scores. Stop after the third action and review the transition.", "Complete five chains in a row without losing guard or stance.", "Every action prepares the next one.", "Where did you insert an unnecessary reset?", "Shadow the A–B–A sequence against fixed target lines, filming one set from the side.", "One fighter opens; the second blocks and attacks; the first blocks and attacks. Trade roles every five cycles.", "Run a three-station chain with a coach calling pace: slow, smooth, then live.", "Academy · F102 Structured Repetition", "Two weapons; camera optional"),
  t("mec-box-block", "Mechanics", "Box-Block Compass", "Protect four target lanes with the smallest reliable closures.", "Mark high-left, high-right, low-left, and low-right lanes. Move the guard to close each lane, returning through center without locking the elbow or exposing the hand.", "A caller names or points to lanes in unpredictable order. Add one controlled return after the defender is consistently early.", "Correctly close sixteen of twenty called lanes while staying relaxed.", "Small motion, complete closure.", "Which lane felt late, weak, or overextended?", "Use four wall marks and move the sword to each closure on an audio or random-number cue.", "Feeder presents slow attacks to four agreed lanes; defender freezes at contact for inspection.", "Create a four-corner callout station; rotate caller, defender, and safety observer.", "SKBC · Single-Sword Guard & Range", "Sword; four markers"),
  t("mec-offhand", "Mechanics", "The Other Hand", "Use off-hand practice to reveal hidden mechanical dependence.", "Perform familiar guard, block, and primary shot patterns with the non-dominant hand. Keep the goal technical; awkwardness is information, not failure.", "Alternate hands every two exchanges. The familiar hand must copy any structural improvement discovered by the other.", "Both hands can execute the chosen pattern slowly without shoulder collapse.", "Borrow skill; do not borrow tension.", "What did the off hand expose about your dominant-side habit?", "Shadow, pell, or target practice entirely with the off hand at low speed.", "Partner feeds one gentle, predictable line while the trainee switches hands between sets.", "Use mirrored stations and compare notes on what each fighter's off hand revealed.", "SKBC · Intermediate Single Sword", "One sword"),
  t("mec-safe-shots", "Mechanics", "Safe Shot Architecture", "Throw committed attacks without giving away the hand, balance, or next action.", "Choose three common shots. For each, identify the opening, hit line, stopping point, and recovery. Practice the whole architecture instead of rehearsing only impact.", "An observer or partner scores the attack for target, balance, hand safety, and recovery—not merely whether it lands.", "Earn three of four quality marks on eight consecutive shots.", "A landed shot can still be a bad repetition.", "Which quality mark disappeared when speed increased?", "Place four checkboxes beside the pell and audit every repetition honestly.", "Partner offers a safe target and a slow primary return; switch roles after ten shots.", "Run a judging lane where one observer calls exactly one correction per fighter.", "Academy · F100 Whole-Fighter Fundamentals", "Sword; target; four counters"),
  t("mec-four-corner", "Mechanics", "Four-Corner Defense", "Build dependable defense against changing height and angle.", "Practice receiving attacks to the four major quadrants. Align guard, elbow, and stance so the block protects the target without opening its opposite.", "Feeder may repeat or change corners. Defender earns the right to return only after two clean defenses.", "Defend two consecutive attacks on eight of ten attempts.", "Protect the target, then earn the return.", "Did you read the line or guess the sequence?", "Use spoken corner cues with shadow blocks, then remove the cue and visualize feeds.", "One feeder uses controlled attacks to four agreed quadrants; reset immediately after unsafe contact.", "Work in trios with one safety observer tracking open opposite corners.", "SKBC · Drills and Training", "Two weapons"),

  t("mov-az", "Movement", "A-to-Z Footwork", "Expand movement vocabulary without sacrificing stance.", "Trace large letters using advances, retreats, lateral steps, pivots, and turns. Keep the torso and guard oriented toward an imagined opponent throughout the letter.", "A caller chooses a letter and interrupts with “freeze.” Check stance width, balance, guard, and facing before continuing.", "Complete five complex letters without crossing feet or losing orientation.", "Every letter ends in a fighting stance.", "Which direction change broke your orientation?", "Mark a safe square and trace letters while facing a fixed target.", "One fighter traces while the partner stays centered and calls freeze checks.", "Use staggered lanes; observers name one clean choice and one unstable turn.", "SKBC · Footwork Theory", "Sword optional; ground markers"),
  t("mov-needling", "Movement", "Needling the Edge", "Learn the smallest entry that creates a real threat.", "Start just outside honest range. Use tiny controlled steps to cross the edge, present one safe threat, and leave before the stance stretches or the feet tangle.", "Partner or target changes distance slightly. The trainee must recalibrate rather than reach farther with the body.", "Enter and exit ten times with the same balanced stance.", "Move the range; do not reach for it.", "Were you defeated by distance or by impatience?", "Work against a pell or hanging target, beginning one finger-width beyond reach.", "Receiver gives a truthful range signal and may drift subtly between repetitions.", "Form a needling lane with one target fighter and two trainees alternating entries.", "SKBC · Drills and Training", "Sword; target optional"),
  t("mov-entry-exit", "Movement", "Entry–Exit Ladder", "Treat escape as part of every attack.", "Build a three-rung ladder: enter without attacking, enter with one attack, then enter–attack–exit. Reset the stance fully between repetitions before making the transitions smooth.", "The defender may answer after the attack. The attacker scores the repetition only by leaving on balance, whether or not the shot lands.", "Eight of ten attacks include a deliberate, safe exit.", "Plan the way out before stepping in.", "Which exits returned you to danger?", "Use two ground lines to rehearse approach and retreat around a static target.", "Partner offers one defensive answer while the attacker practices clearing range.", "Run paired lanes with an exit gate and an observer stationed at the gate.", "Academy · F104 Range & Recovery", "Sword; two line markers"),
  t("mov-lateral", "Movement", "Lateral Formation", "Create new attack lines without drifting out of structure.", "Move laterally around a central point in short steps. Reorient hips, shoulders, and guard after each move instead of letting the body face away from the threat.", "Add an attack only after the new angle is established. The central fighter turns naturally but does not chase.", "Create six useful angles while remaining ready to move either direction.", "Move, reorient, then act.", "Did the weapon arrive before the body was ready?", "Circle a cone, tree, or pell and freeze every quarter turn to inspect facing.", "One partner anchors the center while the mover works both directions.", "Create a compass drill with four outside fighters rotating around one center.", "SKBC · Footwork Fundamentals", "Sword; central marker"),
  t("mov-foot-dominance", "Movement", "Foot Dominance", "Win the positional relationship between lead feet.", "From matched stances, explore how small outside and inside steps change access to targets. Do not attack until you can name which foot relationship you are creating.", "Allow one attack after a fighter establishes the called foot relationship. Reset after every committed exchange.", "Deliberately create the chosen relationship in seven of ten starts.", "Win the feet before asking the sword.", "Which foot position made your usual shot easier or harder?", "Use two pairs of footprint markers and step between inside, neutral, and outside relationships.", "Partners mirror slowly, each trying to establish the called relationship without contact.", "Pairs work inside marked boxes while a caller changes the desired relationship.", "SKBC · Footwork Theory", "Foot markers; swords optional"),
  t("mov-pivot", "Movement", "Pivot & Reorient", "Turn without surrendering the opponent or the stance.", "Practice quarter and half pivots around each foot. After every turn, point eyes, sternum, guard, and lead foot back toward the threat before moving again.", "A partner circles or changes approach angle. The trainee may only defend after completing a clean reorientation.", "Ten turns finish balanced and threat-facing.", "The turn is unfinished until you can fight.", "Which pivot left your hips or guard behind?", "Use a compass of four markers and pivot toward randomized audio cues.", "Partner walks a wide circle and changes direction while the trainee stays centered.", "One center fighter tracks rotating callers; move slowly and prioritize safe spacing.", "SKBC · Footwork Fundamentals", "Four markers; sword optional"),
  t("mov-stance-fire", "Movement", "Stance Under Fire", "Preserve the foundation while choices arrive faster.", "Move through advance, retreat, and lateral patterns while periodically checking foot width, knee comfort, torso height, and the ability to move again.", "Feeder presents safe attacks during movement. Defender may block but cannot plant permanently or widen into immobility.", "Maintain recoverable stance through three one-minute rounds.", "A stance is good only if it can become the next stance.", "What changed first under pressure: width, height, or balance?", "Use interval cues to change direction and freeze-check posture.", "Feeder adds slow threats while matching the mover's intensity.", "Run a moving corridor with one feeder, one defender, and one posture observer.", "SKBC · Footwork Fundamentals", "Sword; safe floor space"),
  t("mov-quiet-feet", "Movement", "Quiet Feet, Fast Choice", "Remove wasted motion so decisions—not bouncing—create speed.", "Stand at the edge of range and make only movement that changes angle, distance, or readiness. Pause after each step and name what it accomplished.", "Run short exchanges where unnecessary steps count against the trainee. Explosive movement is allowed; purposeless movement is not.", "Complete five exchanges with no unaccounted step.", "Stillness is also a footwork choice.", "Which movement spent energy without changing the problem?", "Shadow-fight in a small box and narrate the purpose of each step.", "Partner observes silently, then identifies one useful and one wasted movement.", "Use observation trios and rotate after three exchanges.", "SKBC · Footwork Theory", "Sword; small marked box"),

  t("geo-range-sphere", "Geometry", "The Range Sphere", "Understand reach as a shoulder-centered volume, not a flat distance.", "Explore the edge of reach across high, low, inside, and outside quadrants. Notice how shoulder position and body angle move the reachable sphere.", "Choose a quadrant before entering. The repetition succeeds only if the feet place the target inside the correct part of the sphere.", "Predict reachable and unreachable quadrants correctly eight of ten times.", "Place the target inside the sphere before swinging.", "Where did your imagined reach differ from the real one?", "Map reach around a pell with tape dots at several heights and angles.", "Partner presents safe targets in changing quadrants while remaining mostly still.", "One target stands center while trainees rotate through predicted quadrants.", "SKBC · Single-Sword Guard & Range", "Sword; target markers"),
  t("geo-range-gates", "Geometry", "Range Gates", "Recognize safe, probing, exchange, and crowded distances.", "Mark four distance gates. Move between them without attacking and name which fighter can threaten, which can counter, and which needs a body adjustment.", "A caller names a gate; fighters must arrive in balance and make one appropriate choice: observe, probe, exchange, or clear.", "Choose the correct action at twelve of sixteen gate calls.", "Every range permits some choices and forbids others.", "At which gate did you pretend a weak option was safe?", "Use floor lines and a target to calibrate each gate against honest reach.", "Partners move between gates while verbally checking mutual threat.", "Set four parallel gates and rotate pairs through caller-led scenarios.", "SKBC · Footwork Theory", "Sword; four line markers"),
  t("geo-lane-closure", "Geometry", "Close the Lane", "Defend by occupying the path an attack must travel.", "Choose one incoming line and place the guard so the attack cannot reach its target without crossing your weapon. Keep the movement economical and the hand protected.", "Feeder varies timing and starting guard while preserving the attack lane. Defender identifies and closes the lane rather than chasing the tip.", "Close the intended lane on eight of ten controlled feeds.", "Defend the road, not the traveler.", "Did you intercept the lane or follow the weapon?", "Visualize attack lines from a pell and place the guard across each path.", "Partner feeds slow, honest lines with a freeze at the moment of closure.", "Use trios: feeder, defender, and line judge positioned safely to the side.", "SKBC · Reads, Setups & Returns", "Two weapons"),
  t("geo-shoulder-center", "Geometry", "Shoulder-Center Map", "Calibrate attacks from the actual pivot point of the weapon arm.", "Use the weapon shoulder as the center of your reach map. Compare what changes when the shoulder turns, rises, drops, or travels past the hips.", "Freeze at several attack positions and decide whether the reach came from good alignment or from collapsing posture.", "Demonstrate three reach changes without sacrificing balance.", "The shoulder draws the map; the feet move the map.", "Which apparent range gain cost too much structure?", "Use a mirror or side video to compare shoulder and hip alignment.", "Partner marks the true end of reach in different stances.", "Pairs map each other while a recorder captures one useful discovery per fighter.", "SKBC · Single-Sword Guard & Range", "Sword; mirror or camera optional"),
  t("geo-outside-angle", "Geometry", "The Outside Angle", "Move off the strongest return line before committing.", "From neutral range, take a small diagonal step that improves access while reducing the opponent's direct answer. Reorient before throwing.", "Defender may make only the most direct return. Attacker experiments with angles until that answer becomes awkward or unavailable.", "Create a useful outside angle in six of eight exchanges.", "Make their best answer travel farther.", "Did the angle reduce danger or merely change the scenery?", "Step around a pell using two diagonal entry marks and one exit mark.", "Partner offers a consistent direct-return guard while attacker explores both sides.", "Run angle lanes with one defender and two alternating attackers.", "Academy · F104 Range & Recovery", "Sword; diagonal markers"),
  t("geo-weapon-shape", "Geometry", "Weapon Geometry", "Read how equipment changes available lanes and defensive space.", "Compare flat, round, long, short, broad, and narrow weapon profiles available to you. Name the lanes each shape naturally occupies and leaves open.", "Fight or simulate one-minute rounds where the only goal is choosing lines suited to the current equipment geometry.", "State one equipment-based opening and verify it safely.", "Read the tool before testing the fighter.", "Which assumption about the equipment proved false?", "Arrange available weapons or silhouettes and map likely open lines on paper.", "Partners take static guards with different equipment while the trainee explains choices.", "Build stations by equipment type; groups rotate and record one finding at each.", "SKBC · Reads, Setups & Returns", "Two varied safe weapons or diagrams"),
  t("geo-cones", "Geometry", "Cones & Quadrants", "See how guard position changes attack and defense coverage.", "Explore extended and recessed guards. Map which quadrants each can reach quickly, which lanes they cover, and what startup motion each attack requires.", "Caller names a quadrant and a guard. Fighter must choose defend, attack, or reposition based on the current geometry.", "Make the defensible choice on twelve of sixteen calls.", "Guard position changes the shape of the next moment.", "Which guard solved one problem while creating another?", "Use four target marks and alternate extended and recessed guard positions.", "Partner holds changing guards while trainee names immediate options before acting.", "One caller controls guard and quadrant prompts for a group response line.", "SKBC · Single-Sword Guard & Range", "Sword; four target marks"),
  t("geo-four-ranges", "Geometry", "Four Ranges, Four Jobs", "Match tactics to long, medium, close, and crowded range.", "Move deliberately through four distances and assign each a job: gather information, threaten, exchange, or clear. Adjust for body and weapon length.", "Run bouts that begin at a called range. The first decision must fit the job of that range before free choices begin.", "Choose a range-appropriate first action in seven of eight starts.", "Do the job of the range you are actually in.", "Where did habit override the geometry?", "Use a fixed target and marked distances to rehearse the four first actions.", "Partner calls the starting range and verifies mutual reach before each exchange.", "Set up four stations, one for each range job, and rotate pairs.", "SKBC · Footwork Theory", "Weapons; four distance marks"),

  t("int-cold-read", "Intelligence", "Cold Read Ledger", "Collect useful facts before either fighter acts.", "Study stance, handedness, foot spread, guard, equipment, height, and visible habits. Separate what you know from what you merely predict.", "Write or speak a three-line ledger: fact, hypothesis, first test. Then run one exchange only to test the hypothesis.", "Make one accurate fact-based prediction in three consecutive opponents or stances.", "Facts first. Story second. Test third.", "Which assumption did you mistake for a fact?", "Analyze photos, video pauses, or your own alternate guards and build three ledgers.", "Partner presents several silent starting stances; trainee states the ledger before movement.", "One model cycles through stances while small groups submit and compare ledgers.", "SKBC · Reads, Setups & Returns", "Notebook; weapons optional"),
  t("int-hot-read", "Intelligence", "Hot Read Probe", "Use low-cost actions to reveal live reactions.", "Choose one safe probe—a range step, guard twitch, half-entry, or visible lane. Observe whether the opponent fights, freezes, retreats, blocks, or counters.", "The first two exchanges cannot score for the trainee; they exist only to ask questions. Build the third exchange from the answers.", "Name one reaction and choose a related third-exchange plan.", "Spend small actions to buy real information.", "Did the probe ask a clear question?", "Shadow an imagined opponent and script three probe–reaction–plan trees.", "Partner responds naturally to probes without trying to disguise every habit.", "Rotate through short three-exchange interviews with a new opponent each round.", "SKBC · Reads, Setups & Returns", "Weapons; notebook optional"),
  t("int-opener-lab", "Intelligence", "Opener Laboratory", "Design opening actions that gather information safely.", "Build three openers: one that tests range, one that tests guard response, and one that tests movement. Rehearse each without requiring a hit.", "Use an unknown opener at the start of each bout. Pause after the first response and state what it taught you.", "Each opener produces a specific observation without reckless commitment.", "An opener begins the conversation; it need not end the fight.", "Which opener gave information at the lowest cost?", "Use a pell and visualize two likely responses to each opener.", "Partner gives varied natural answers and confirms what the opener communicated.", "Create opener stations; fighters rotate and record one useful response at each.", "SKBC · Reads, Setups & Returns", "Weapon; three opener cards"),
  t("int-tell-hunt", "Intelligence", "Tell Hunt", "Connect repeated body language to likely choices.", "Observe shoulders, feet, guard motion, breath, and preferred reset. Track one behavior that appears before the same action more than once.", "Do not exploit the tell until it appears twice. On the third appearance, choose a controlled answer and verify the prediction.", "Correctly predict one action from a repeated tell.", "A tell becomes evidence only after repetition.", "What else could have caused the same signal?", "Watch a short fight clip or film your own shadow patterns and mark repeated pre-actions.", "Partner fights lightly and honestly while trainee hunts one tell at a time.", "One pair spars while the group records possible tells, then compares after the round.", "SKBC · Opponent Analysis", "Weapons; camera optional"),
  t("int-plan-adapt", "Intelligence", "Plan–Check–Adapt", "Keep a plan long enough to test it and light enough to change it.", "State a one-sentence plan based on current evidence. Define what success and failure would look like before the exchange.", "Run three bouts. After each, keep the plan, adjust one part, or abandon it—but name the evidence that justifies the choice.", "Every change can be traced to observed evidence rather than frustration.", "A plan serves the fight; the fight does not serve the plan.", "Did you adapt too early, too late, or without evidence?", "Use imagined scenarios or fight video and pause after each exchange to update a written plan.", "Partner gives honest rounds and asks only: keep, adjust, or replace—and why?", "Use coaching trios; observer records when evidence and plan diverge.", "SKBC · Opponent Analysis", "Weapons; note card"),
  t("int-style-analysis", "Intelligence", "Style Analysis", "Turn many observations into a simple working model.", "Assess preferred range, pace, guard, initiative, favorite target, recovery, and response to pressure. Choose the two traits that matter most now.", "Build one strategy that attacks a preference and one fallback that denies it. Test each in a short round.", "The final model fits in two sentences and changes one tactical choice.", "Compress information until it becomes usable.", "Which detail was interesting but tactically irrelevant?", "Analyze a fighter video, fictional matchup, or your own two common styles.", "Partners alternate styles and let the trainee identify the controlling traits.", "Small teams analyze one sparring pair, then compare their two-sentence models.", "SKBC · Opponent Analysis", "Notebook; weapons optional"),
  t("int-three-exchanges", "Intelligence", "The First Three Exchanges", "Give early exchanges distinct information jobs.", "Assign exchange one to range, exchange two to defensive response, and exchange three to tempo or initiative. Rehearse a safe question for each.", "Fight three-exchange sets. No tactical commitment may ignore the information gathered in the prior exchange.", "State three observations and one coherent fourth-exchange plan.", "Let each exchange answer one question.", "Which question was too vague to guide the next choice?", "Write three exchange scripts against common archetypes and shadow them.", "Partner runs repeated four-exchange sets and debriefs after each.", "Rotate opponents after every set so the process—not memorization—gets trained.", "Academy · F206 Tactical Learning", "Weapons; three counters"),
  t("int-return-tree", "Intelligence", "Return Tree", "Predict primary, secondary, and tertiary answers from a position.", "Freeze after a block or guard reaction. List the safest return, the next-likeliest return, and the unusual return. Map one answer to each.", "Resume from the freeze with the defender choosing among the three returns. Attacker must read the startup rather than guess.", "Correctly identify and answer two of three return branches.", "Prepare branches, then read the one that grows.", "Which branch did you ignore because it was less common?", "Use photos or self-posed freeze positions and sketch three return branches.", "Run block–strike with a pause; name branches before the return continues.", "Use one frozen pair as a live diagram while the group builds and tests the tree.", "SKBC · Reads, Setups & Returns", "Two weapons; note card"),

  t("dec-feint-real", "Deception", "A Feint That Could Land", "Make false attacks share the beginning of true ones.", "Choose one real attack and repeat it until the setup, body language, and first motion are consistent. Then stop or redirect only after the opponent would need to answer.", "Mix real and feinted versions. The receiver reports whether they could distinguish them before the decision point.", "The receiver reacts early to at least six of ten feints.", "Sell the truth before changing the ending.", "Which early detail betrayed the false version?", "Use video to compare five real attacks and five feints frame by frame.", "Receiver gives honest defensive reactions and immediate feedback.", "Work in trios: attacker, receiver, and observer watching only the setup.", "SKBC · Fakes, Baits & Feints", "Weapon; camera optional"),
  t("dec-bait-lane", "Deception", "Bait the Lane", "Offer a tempting target while preparing a safe answer.", "Deliberately open one lane from an otherwise credible guard. Define the expected attack and rehearse the closure and return before inviting it.", "Receiver may take the bait or refuse it. The baiter must stay safe and avoid forcing the trap after the information changes.", "Create the intended attack three times without being struck through the bait.", "An offered opening is not permission to become careless.", "Was the opening tempting, obvious, or simply unsafe?", "Pose the bait against a pell, then shadow both the expected and refused branches.", "Partner chooses freely whether to attack the offered lane.", "Rotate baiter, attacker, and safety observer every five attempts.", "SKBC · Fakes, Baits & Feints", "Two weapons"),
  t("dec-condition-break", "Deception", "Condition & Break", "Build an expectation through honest repetition, then change one finish.", "Present the same setup and finish several times at safe intensity. Watch for the opponent's response becoming faster or automatic.", "Preserve the setup but change exactly one element—target, timing, depth, or return—after the conditioned response appears.", "Opponent commits to the expected answer before the changed finish.", "Repeat enough to teach; change little enough to deceive.", "Did you break the pattern before it truly existed?", "Use a target and alternate a four-repetition pattern with one planned change-up.", "Partner reports when the response began to feel automatic.", "In a rotation, each fighter gets one short pattern-building set and one break attempt.", "SKBC · Fakes, Baits & Feints", "Weapons; five counters"),
  t("dec-change-up", "Deception", "The Change-Up", "Use a familiar beginning with a different pace or ending.", "Select a common combination. Keep the opener unchanged while testing a delayed second action, faster second action, shortened depth, or alternate target.", "Opponent knows the base combination but not which single change-up will appear.", "The changed element creates hesitation without damaging your own structure.", "Change one variable; keep the rest believable.", "Which change-up improved the situation rather than adding novelty?", "Shadow the base combination four times, then one variation, and compare rhythm.", "Partner defends the known base pattern while the trainee introduces one variation.", "Run change-up stations for timing, target, and depth; rotate every two minutes.", "SKBC · Fakes, Baits & Feints", "Weapon; target optional"),
  t("dec-threat-hold", "Deception", "Threat Without Release", "Use credible threat to move the opponent without spending the attack.", "Enter the edge of range with a prepared line and balanced stance. Hold just long enough to observe the response, then leave or convert without lunging from impatience.", "Score the repetition when the opponent changes guard, feet, or tempo in response to the held threat—even if no attack is thrown.", "Create a visible reaction on six of ten entries while remaining safe.", "A threat is an action if it changes their choices.", "Could you hold the threat without freezing yourself?", "Work a pell from edge range and practice enter–hold–exit cycles.", "Partner responds naturally and names what made the threat credible.", "Use a reaction line: one threatening fighter moves down a row of fresh defenders.", "SKBC · Fakes, Baits & Feints", "Weapons"),
  t("dec-double-meaning", "Deception", "Double Meaning", "Build one setup that supports two honest attacks.", "Choose two attacks with the same first step, guard motion, or shoulder cue. Practice both until the shared beginning is truly shared.", "Receiver must commit after the shared cue. Attacker selects the finish from the actual defensive movement.", "Both finishes remain clean, safe, and available from the decision point.", "One beginning. Two truthful endings.", "Did you choose from the reaction or decide too early?", "Use video or a mirror to match the shared beginning of both attacks.", "Partner reacts after the shared cue and varies the defensive answer.", "Work in trios with the observer identifying the earliest visible difference.", "Academy · F208 Setups & Choice", "Weapons; camera optional"),
  t("dec-tempo-theft", "Deception", "Tempo Theft", "Manipulate when the opponent expects the next action.", "Rehearse the same safe action with steady rhythm. Then add a pause, acceleration, or early release without telegraphing through tension.", "Opponent may act during the altered beat. Trainee must preserve defense and abandon the plan if the timing no longer supports it.", "Create three clean timing errors without overcommitting.", "Change the beat, not the body language.", "Which tempo change surprised them and which only rushed you?", "Use a metronome or spoken count, then omit or compress one beat.", "Partner moves or defends on expected beats and gives honest timing feedback.", "A caller sets group rhythm and secretly cues one fighter's change.", "SKBC · Footwork & Tempo", "Weapon; metronome optional"),
  t("dec-pattern-poison", "Deception", "Pattern Poison", "Make an opponent doubt a response that was previously reliable.", "Identify a response they trust. Safely demonstrate that response succeeding, then create one controlled counter that punishes automatic use without requiring force or speed.", "Alternate ordinary exchanges with rare counter attempts. The goal is hesitation and choice, not repeated surprise attacks.", "Opponent begins checking before using the conditioned response.", "The best trap changes the next decision.", "Did your counter teach caution or merely win once?", "Write a response–counter pair and shadow both sides before adding a target.", "Partner repeats a chosen response and reports when confidence changes.", "Small groups design one safe pattern-poison scenario and teach it to another group.", "SKBC · Fakes, Baits & Feints", "Weapons; note card"),

  t("drill-slow-fast", "Drill Discipline", "Slow Before Fast", "Earn speed by preserving the structure speed usually destroys.", "Choose one short pattern and perform it at a pace where every detail is controllable. Increase speed only after five consecutive clean repetitions.", "At each speed increase, an observer or checklist audits the same success standard. Drop one level immediately when quality falls.", "Reach the fastest clean pace without skipping a failed level.", "Speed is permission earned by clean structure.", "At what pace did quality first change?", "Use video and a simple slow–medium–fast ladder against a pell or air target.", "Partner feeds predictable actions and controls the pace ladder.", "One coach runs synchronized lanes and calls advancement only after standards are met.", "SKBC · Drills and Training", "Weapon; checklist"),
  t("drill-constraint", "Drill Discipline", "Constraint Round", "Force one skill to appear by temporarily narrowing the game.", "Choose a constraint tied to the goal: only diagonal entries score, block twice before returning, exit after every attack, or forbid a favorite option.", "Fight under the rule even when breaking it would win. Increase freedom only when the desired behavior appears reliably.", "Follow the constraint for the entire round and produce the target behavior three times.", "Honor the rule when it costs you.", "Did the constraint expose a skill gap or a motivation gap?", "Shadow-fight in a marked space and self-call any broken rule.", "Partner enforces one agreed constraint and pauses only for safety or clarity.", "Run short constraint stations with one rule posted at each.", "Academy · Deliberate Practice Doctrine", "Weapons; rule card"),
  t("drill-pressure-ladder", "Drill Discipline", "Pressure Ladder", "Carry one skill from clean repetition into live choice.", "Define four rungs: cooperative pattern, variable feed, constrained sparring, and open test. Keep the skill cue unchanged across every rung.", "Advance only when the skill remains visible. If it disappears, return one rung, repair it, and climb again.", "The same cue appears successfully in the open test at least twice.", "Change the pressure, not the purpose.", "On which rung did conscious skill become habit—or vanish?", "Use target randomness, timer pressure, and visualization as the first three rungs before a future live test.", "Partner controls variability and records when the cue stops appearing.", "Assign one group to each rung and move fighters forward or back by evidence.", "SKBC · Training to Improve", "Weapons; four rung markers"),
  t("drill-chunk", "Drill Discipline", "Chunk the Chain", "Join small reliable actions into one usable sequence.", "Break a sequence into two-action chunks. Practice each chunk cleanly, then overlap the ending of one with the beginning of the next.", "Randomly begin from different chunks so the sequence becomes a network of usable actions rather than a memorized recital.", "Start from any named chunk and complete the chain without a reset.", "Build small pieces; connect shared edges.", "Which transition was never truly learned on its own?", "Use written action cards and shadow the sequence from randomized starting cards.", "Partner feeds the starting condition for each chunk.", "Teams build one chain, then another team stress-tests the transitions.", "SKBC · Training to Improve", "Weapon; action cards"),
  t("drill-rep-audit", "Drill Discipline", "Clean Repetition Audit", "Measure practice quality instead of counting motion.", "Define three visible quality checks for one action. Complete sets of ten, recording which check failed first on every imperfect repetition.", "After each set, change only the most common failure. Do not add new corrections until the pattern improves.", "Raise clean repetitions by at least two between the first and final set.", "Count what you are willing to correct.", "Was fatigue, confusion, or pace driving the errors?", "Use a pell, counters, and a three-column scorecard.", "Partner performs or feeds while the observer records without interrupting every rep.", "Audit trios rotate performer, feeder, and recorder after each set.", "Academy · Measuring Improvement", "Weapon; ten counters; scorecard"),
  t("drill-designer", "Drill Discipline", "Drillwright", "Design a practice that isolates one real fighting problem.", "Write a drill with five parts: problem, allowed actions, roles, success standard, and stop condition. Remove anything that does not expose the chosen problem.", "Run a short pilot. Ask whether success in the drill would plausibly improve the real fight, then revise one rule.", "Another fighter can run the drill from your explanation and measure success.", "A drill is a question with visible evidence.", "Which rule created noise instead of learning?", "Design and dry-run the roles aloud using objects or written tokens.", "Partner pilots the drill and explains what behavior it actually rewarded.", "Small teams exchange drills, run them cold, and return one revision.", "Academy · Instructor Training", "Note card; gear required by design"),
  t("drill-error", "Drill Discipline", "Error Isolation", "Turn one repeated failure into a trainable problem.", "Describe the failure without judgment: what happened, when, and under what condition. Recreate the smallest version of that moment at low speed.", "Add one variable at a time—timing, target, movement, then live choice—until the failure reappears. Repair at that edge.", "Identify the first variable that triggers the error and improve it across one set.", "Shrink the problem until you can see it.", "Was the apparent error actually caused one action earlier?", "Use fight notes or video to reconstruct the moment in shadow form.", "Partner recreates the triggering feed consistently and adds variables by agreement.", "A fighter describes a problem; the group builds and tests the smallest useful recreation.", "SKBC · Training to Improve", "Weapons; note card"),
  t("drill-transfer", "Drill Discipline", "Transfer Test", "Discover whether a practiced skill survives outside its drill.", "Perform the skill in its familiar drill, then change one context feature: opponent, stance, weapon, starting range, or tempo.", "Run an open test where the skill is useful but never required. Count only appearances that arise from a real choice.", "The skill appears cleanly twice in an unfamiliar context.", "Practice is proven when the cue survives change.", "Did the drill teach the skill, or only the drill's pattern?", "Change target height, starting side, rhythm, or environment between sets.", "Partner varies one context factor while preserving safe intensity.", "Fighters rotate opponents and stations while carrying the same private cue.", "Academy · Deliberate Practice Doctrine", "Weapons; varied station markers"),

  t("lead-one-correction", "Leadership", "One Correction", "Give feedback a fighter can use on the very next repetition.", "Observe without interrupting for one short set. Choose the single correction with the largest effect and phrase it as a visible action.", "The learner attempts the correction immediately. Ask what changed before offering explanation or another note.", "The learner can repeat the correction in their own words and show it once.", "One clear action beats five accurate lectures.", "Did your correction change behavior or display knowledge?", "Review a fight clip and practice writing one observable correction in twelve words or fewer.", "Observe a partner's set, offer one correction, then let them teach it back.", "Use feedback trios and rotate coach, fighter, and observer.", "Academy · Instructor Training", "Optional weapon; observation card"),
  t("lead-teach-back", "Leadership", "Teach It Back", "Reveal understanding by making another fighter able to use it.", "Explain one concept in one sentence, demonstrate it once, and give the learner a small repetition with a clear standard.", "Ask the learner to explain the concept back and choose the next difficulty. Correct only the missing piece.", "The learner can state the idea and perform its basic action without prompting.", "Teaching is measured in the learner.", "What part became unclear when someone else had to use it?", "Record a two-minute lesson to your future self and critique its clarity.", "Teach one narrow skill, then switch roles and compare teaching choices.", "Pairs teach while roaming observers record the clearest cue they hear.", "Academy · Preceptor Method", "Gear for chosen lesson"),
  t("lead-first-win", "Leadership", "The Beginner’s First Win", "Create early success that teaches a truthful foundation.", "Choose a simple action a new fighter can perform safely. Remove pressure, demonstrate once, and give enough repetition for visible improvement.", "Add one honest challenge without taking away the success. Praise the specific behavior, not talent or rank.", "The learner succeeds, can name why, and wants another attempt.", "Make the first victory real and repeatable.", "Did you simplify the problem or secretly solve it for them?", "Design a five-minute first lesson and rehearse both demonstration and safety language.", "Run the lesson with consent; invite the partner to identify confusing steps.", "Build beginner stations with one foundation and one modest challenge each.", "Academy · Cadet Onboarding", "Safe loaner gear"),
  t("lead-rotation", "Leadership", "Run the Yard", "Keep a group rotation safe, active, and focused.", "State the goal, roles, rotation signal, intensity, and stop condition before anyone begins. Demonstrate the drill from the learner's viewpoint.", "Run two short rotations. Watch spacing, idle time, safety, and whether the stated skill remains visible.", "Every fighter knows where to stand, when to rotate, and what success looks like.", "Clarity before lay-on.", "Where did the group need information you had not given?", "Lay out a rotation with markers or a sketch and speak the briefing aloud.", "Partner role-plays a confused participant and tests the instructions.", "Run the complete rotation, then ask one participant to brief it back.", "Academy · Session Leadership", "Markers; gear for chosen drill"),
  t("lead-safety-speed", "Leadership", "Safety Before Speed", "Model intensity control as a mark of skilled leadership.", "Define the safe speed and contact level for the current drill. Demonstrate both correct intensity and an exaggerated unsafe example without contact.", "Pause and reset the instant control degrades. Name the action needed to resume instead of assigning blame.", "The group maintains agreed intensity through the full round.", "Control is part of technique.", "Did your intervention make the next repetition safer and clearer?", "Write and rehearse a concise safety brief for one common drill.", "Partner varies speed near the limit while the leader practices timely resets.", "Run a short drill with a designated safety lead and a shared stop signal.", "Academy · Safety & Culture", "Appropriate safe gear"),
  t("lead-peer-review", "Leadership", "Peer Review", "Exchange useful observation without turning feedback into rank.", "Agree on one success standard before the set. Observer records evidence for that standard only, then asks the fighter for their own assessment first.", "Compare the two observations and choose one next repetition. Avoid debating style choices unrelated to the standard.", "Feedback contains one observation, one question, and one next action.", "Evidence first; ego last.", "Where did preference disguise itself as correction?", "Review your own clip twice: first as fighter, then as neutral observer.", "Alternate fighter and observer roles around one agreed standard.", "Trios rotate and compare self-assessment with outside evidence.", "Academy · Whole-Fighter Doctrine", "Optional weapons; observation card"),
  t("lead-build-session", "Leadership", "Forge for Another", "Turn another fighter's real need into a focused practice.", "Ask what happened, why they think it happened, and what they can control. Choose one narrow training target rather than solving their whole game.", "Build a primer, focused drill, pressure test, and reflection. Let the learner help set the standard and intensity.", "The session addresses the stated problem and ends with one next action.", "Coach the fighter in front of you, not your favorite lesson.", "Which part came from their evidence and which came from your assumptions?", "Use a written scenario to design a twenty-minute session for an imagined fighter.", "Interview a partner and build a short session together.", "Small teams receive different fighter profiles and present a focused plan.", "Academy · Instructor Training", "Planning card; session gear"),
  t("lead-carry-school", "Leadership", "Carry the School Home", "Convert personal learning into a repeatable local practice.", "Choose one lesson from recent training. Rewrite it for your park's space, equipment, experience, and available time while preserving its purpose.", "Pilot the adapted lesson, collect one piece of learner evidence, and revise the part that caused the most friction.", "Another leader can repeat the lesson from your notes.", "Tradition lives when useful knowledge can travel.", "What had to change locally, and what could not change without losing the lesson?", "Create a one-page lesson card and rehearse the opening brief.", "Partner runs the lesson from your notes while you observe silently.", "Teach the adapted lesson to the group and appoint a second person to lead the next round.", "Academy · Preceptor Continuity", "Lesson card; local gear"),
];

export const templatesFor = (domain: DomainName) =>
  FORGE_TEMPLATES.filter((template) => template.domain === domain);

