export const weeklyPlan = [
  {
    day: 'Monday',
    short: 'Mon',
    focus: 'Mechanics',
    system: 'Neural',
    metric: 'Accuracy %',
    color: 'rose',
    goal: 'Perfect mechanics through one-shot precision work.',
    phases: [
      'Mobility and wrist/elbow/shoulder prep',
      'Shot isolation: 1 shot only',
      'Pell work across 4 quadrants',
      'Light spar: score only with practiced shot',
      'Review form breakdown and clean-hit rate',
    ],
    drillIdeas: ['10 slow', '20 moderate', '20 explosive', '20 fatigued', '90% clean hit gate'],
  },
  {
    day: 'Tuesday',
    short: 'Tue',
    focus: 'Footwork',
    system: 'Movement',
    metric: 'Position Wins %',
    color: 'sky',
    goal: 'Build range control, angle creation, and safer entries.',
    phases: [
      'Dynamic movement warm-up',
      'Ladder / cone / marker patterns',
      'Range entry and exit drill',
      'Constraint spar: no strike unless angle created first',
      'Review overcommitments and resets',
    ],
    drillIdeas: ['Shuffle matrix', 'Lateral burst', 'Gather/lunge chain', 'Retreat/reentry', '45 degree entry'],
  },
  {
    day: 'Wednesday',
    short: 'Wed',
    focus: 'Tactics',
    system: 'Cognitive',
    metric: 'Correct Reads %',
    color: 'violet',
    goal: 'Train the combat computer with reads, returns, and setups.',
    phases: [
      'Film study and observation',
      'Prediction drill: call opener before block',
      'Return chains and tertiary setups',
      'Tactical spar: win only by setup',
      'Review patterns, baits, and punish windows',
    ],
    drillIdeas: ['Cold reads', 'Hot reads', 'Ammo chains', 'Block to return', 'Block to bait to punish'],
  },
  {
    day: 'Thursday',
    short: 'Thu',
    focus: 'Pressure',
    system: 'Stress',
    metric: 'Fatigue Win Rate %',
    color: 'amber',
    goal: 'Maintain form and decision quality while tired.',
    phases: [
      'Warm-up and activation',
      'Conditioning circuit',
      'Fatigue spar immediately after circuit',
      'First-to-10 tournament simulation',
      'Review mistakes made under fatigue',
    ],
    drillIdeas: ['Lunges x20', 'Burpees x10', 'Sprint x20m', 'Shadow swings x30', 'Pressure reset ritual'],
  },
  {
    day: 'Friday',
    short: 'Fri',
    focus: 'Weakness',
    system: 'Adaptive',
    metric: 'Weakness Success %',
    color: 'emerald',
    goal: 'Attack the single weakest link from the week.',
    phases: [
      'Warm-up',
      'Weak skill isolation',
      'Repetition and correction drill',
      'Controlled spar around that weakness',
      'Review what improved and what still breaks',
    ],
    drillIdeas: ['Bad blocks', 'Slow footwork', 'Panic under pressure', 'Weak offside', 'Range mistakes'],
  },
  {
    day: 'Saturday',
    short: 'Sat',
    focus: 'Competition',
    system: 'Performance',
    metric: 'Placement',
    color: 'fuchsia',
    goal: 'Replicate tournament conditions with scorekeeping and pressure.',
    phases: [
      'Ritual warm-up',
      'Bracket sparring',
      'More bracket sparring / adaptation',
      'Finals simulation',
      'Immediate post-analysis',
    ],
    drillIdeas: ['Single elimination', 'Bystanders watching', 'Score kept', 'Warm-up ritual', 'Rapid notes'],
  },
  {
    day: 'Sunday',
    short: 'Sun',
    focus: 'Recovery',
    system: 'Recovery',
    metric: 'Recovery Score',
    color: 'slate',
    goal: 'Improve without fatigue and reset for the next cycle.',
    phases: [
      'Mobility',
      'Visualization',
      'Film review',
      'Journal and planning',
      'Choose next weakness target',
    ],
    drillIdeas: ['Highlight reel', 'Failure rehearsal', 'Short video review', 'Journal wins/problems', 'Next week plan'],
  },
]

export const phaseWeeks = [
  { week: 'Week 1', phase: 'Accumulation', intensity: 60, volume: 85, focus: 'Volume + Technique' },
  { week: 'Week 2', phase: 'Accumulation', intensity: 78, volume: 88, focus: 'Skill Load + Pressure' },
  { week: 'Week 3', phase: 'Intensification', intensity: 90, volume: 62, focus: 'Performance + Speed' },
  { week: 'Week 4', phase: 'Deload', intensity: 35, volume: 35, focus: 'Recovery + Analysis' },
]

export const library = {
  Mechanics: ['High cross reps', 'Flat wrap reps', 'Reverse wrap lines', 'Pell quadrants', '10,000-shot tracking'],
  Footwork: ['Ghost line shuffle', 'Silent Thunder gather step', 'Commitment Test step-reset', 'Deep Hit and Fade lunge', 'Circle Cutter lateral drill'],
  Tactics: ['Prediction drill', 'Ammo drill', 'Observe-pattern journal', 'Setup-only spar', 'OODA loop bait reps'],
  Pressure: ['Circuit to fatigue spar', 'First-to-10', 'Comeback drills', 'Consequence rounds', 'Breathing reset'],
  Weakness: ['Mistake-specific isolation', 'Wrong-then-right reps', 'Slow-mo correction', 'Constraint spar', 'Targeted pelling'],
  Competition: ['Bracket simulation', 'Warm-up ritual', 'Goal card', 'Scorekeeping', 'Post-fight debrief'],
  Recovery: ['Mobility flow', 'Highlight reel visualization', 'Short film audit', 'Journal reflection', 'Planning checklist'],
}

export const demoLogs = [
  {
    date: '2026-04-14',
    day: 'Monday',
    focus: 'Mechanics',
    duration: 90,
    mainDrill: 'High cross reps',
    metricType: 'Accuracy %',
    result: '82',
    success: 'No',
    energy: 7,
    confidence: 6,
    win: 'Cleaner elbow path',
    problem: 'Still telegraphing',
  },
  {
    date: '2026-04-15',
    day: 'Tuesday',
    focus: 'Footwork',
    duration: 60,
    mainDrill: 'Gather/lunge chain',
    metricType: 'Position Wins %',
    result: '64',
    success: 'Yes',
    energy: 8,
    confidence: 7,
    win: 'Better angle entries',
    problem: 'Late retreat',
  },
  {
    date: '2026-04-16',
    day: 'Wednesday',
    focus: 'Tactics',
    duration: 75,
    mainDrill: 'Prediction drill',
    metricType: 'Correct Reads %',
    result: '58',
    success: 'No',
    energy: 6,
    confidence: 5,
    win: 'Better pattern notes',
    problem: 'Too slow on returns',
  },
]
